version: '3.8'

services:
  rework-tracker:
    build:
      context: .
      dockerfile: Dockerfile.github
    container_name: rework-tracker-app
    ports:
      - "5001:5001"
      - "5002:5002"
    volumes:
      # Bind mount: DB file saved directly to the local host folder
      - ./src/store/serverDataBase/data:/usr/src/app/src/store/serverDataBase/data
      - docs_data:/usr/src/app/src/store/serverDataBase/docs
      - pictures_data:/usr/src/app/src/store/serverDataBase/pictures
      - logs_data:/usr/src/app/src/store/serverDataBase/logs
    restart: unless-stopped

volumes:
  docs_data:
  pictures_data:
  logs_data:
