# Generated by Django 6.0.3 on 2026-03-20 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductNameAndRev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rev', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PCB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcb_number', models.CharField(max_length=100, unique=True)),
                ('bom_number', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('last_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_owned_pcbs', to='rework_tracker.owner')),
                ('product_name_and_rev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcbs', to='rework_tracker.productnameandrev')),
            ],
        ),
        migrations.CreateModel(
            name='Rework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rework_number', models.CharField(max_length=100, unique=True)),
                ('rework_description', models.TextField()),
                ('rework_status', models.CharField(max_length=100)),
                ('rework_date', models.DateTimeField(auto_now_add=True)),
                ('rework_picture', models.ImageField(blank=True, null=True, upload_to='rework_pictures/')),
                ('pcb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reworks', to='rework_tracker.pcb')),
                ('rework_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reworks', to='rework_tracker.owner')),
            ],
        ),
    ]
